### ISSUE TITLE
Operator_code and registration_state from ModemManager

### ISSUE THREAD

**Issue by yavordobrev** [soerenmeier/linux-info#2]
For my current project I need the operator_code and registration_state of a ModemManager connection. Those can be easily added, as the underlying functions are already there. Could you please add those? Alternatively I could contribute the change, if you like...

**Comment by soerenmeier** [comment]
Hi @yavordobrev thanks for using this crate. I just published v0.1.16 with the added functions. Let me know if there is a problem.
Cheers Sören
